import { useState, useEffect } from 'react'
import api from '../../services/api'
import { Loader2, Utensils, ChevronDown, ChevronUp, FileText, Download } from 'lucide-react'

export default function TraineeNutrition() {
  const [plans, setPlans] = useState([])
  const [loading, setLoading] = useState(true)
  const [expanded, setExpanded] = useState(null)

  useEffect(() => {
    api.get('/trainee/nutrition-plans').then(r => { setPlans(r.data); if (r.data.length > 0) setExpanded(r.data[0].id) }).finally(() => setLoading(false))
  }, [])

  if (loading) return <div className="flex justify-center py-20"><Loader2 size={40} className="animate-spin text-gym-primary" /></div>

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-black text-gym-text">Nutrition Plans</h1>
        <p className="text-gym-muted text-sm">{plans.length} plan{plans.length !== 1 ? 's' : ''}</p>
      </div>

      {plans.length === 0 ? (
        <div className="card text-center py-12">
          <Utensils size={48} className="mx-auto mb-3 text-gym-primary opacity-30" />
          <p className="text-gym-muted">No nutrition plans yet</p>
          <p className="text-gym-muted text-sm mt-1">Wait for your coach to add a plan or subscribe to a premium package</p>
        </div>
      ) : (
        <div className="space-y-4">
          {plans.map(plan => (
            <div key={plan.id} className="card p-0 overflow-hidden">
              <button
                className="w-full flex items-center gap-4 p-4 hover:bg-white/5 transition-colors"
                onClick={() => setExpanded(expanded === plan.id ? null : plan.id)}
              >
                <span className="text-2xl">🥗</span>
                <div className="flex-1 text-left">
                  <h3 className="font-bold text-gym-text">{plan.title}</h3>
                  <p className="text-gym-muted text-sm">
                    {plan.isAutoGenerated ? `📋 ${plan.coachName}` : `👨‍💼 ${plan.coachName}`} •
                    {new Date(plan.createdAt).toLocaleDateString('en-GB')}
                  </p>
                </div>
                <div className="flex items-center gap-3">
                  <span className="badge bg-gym-primary/20 text-gym-primary text-xs">{plan.meals.length} meals</span>
                  {expanded === plan.id ? <ChevronUp size={18} className="text-gym-muted" /> : <ChevronDown size={18} className="text-gym-muted" />}
                </div>
              </button>

              {expanded === plan.id && (
                <div className="border-t border-gym-border p-4 space-y-3 bg-gym-bg">
                  {plan.description && <p className="text-gym-muted text-sm">{plan.description}</p>}

                  {/* Attachment */}
                  {plan.attachmentBase64 && (
                    <div className="w-full">
                      {plan.attachmentType === 'image' ? (
                        <img src={plan.attachmentBase64} alt="Diet Plan" className="w-full rounded-xl object-contain" />
                      ) : (
                        <a
                          href={plan.attachmentBase64}
                          download={`nutrition-plan-${plan.id}.${plan.attachmentType === 'pdf' ? 'pdf' : 'docx'}`}
                          className="flex items-center gap-3 bg-gym-card rounded-xl p-4 hover:border-gym-primary border border-gym-border transition-colors"
                        >
                          <FileText size={28} className={plan.attachmentType === 'pdf' ? 'text-red-400' : 'text-blue-400'} />
                          <div className="flex-1">
                            <p className="font-semibold text-gym-text text-sm">Diet Plan File</p>
                            <p className="text-gym-muted text-xs">{plan.attachmentType?.toUpperCase()}</p>
                          </div>
                          <Download size={18} className="text-gym-primary" />
                        </a>
                      )}
                    </div>
                  )}

                  {/* Totals */}
                  {plan.meals.some(m => m.calories) && (
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                      {[
                        ['Calories', `${plan.meals.reduce((s, m) => s + (m.calories || 0), 0)} kcal`, 'text-gym-primary'],
                        ['Protein', `${plan.meals.reduce((s, m) => s + (m.protein || 0), 0).toFixed(0)}g`, 'text-blue-400'],
                        ['Carbs', `${plan.meals.reduce((s, m) => s + (m.carbs || 0), 0).toFixed(0)}g`, 'text-yellow-400'],
                        ['Fats', `${plan.meals.reduce((s, m) => s + (m.fats || 0), 0).toFixed(0)}g`, 'text-red-400'],
                      ].map(([k, v, c]) => (
                        <div key={k} className="bg-gym-card rounded-lg p-2 text-center">
                          <p className="text-gym-muted text-xs">{k}</p>
                          <p className={`font-bold text-sm ${c}`}>{v}</p>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Meals */}
                  <div className="space-y-3">
                    {plan.meals.map(meal => (
                      <div key={meal.id} className="bg-gym-card rounded-xl p-4">
                        <div className="flex items-center justify-between mb-2">
                          <h4 className="font-bold text-gym-primary">{meal.mealName}</h4>
                          {meal.time && <span className="text-gym-muted text-xs">🕐 {meal.time}</span>}
                        </div>
                        {meal.foods && <p className="text-gym-text text-sm leading-relaxed">{meal.foods}</p>}
                        {meal.calories && (
                          <div className="flex gap-3 mt-2 text-xs text-gym-muted">
                            <span>🔥 {meal.calories} kcal</span>
                            {meal.protein && <span>💪 {meal.protein}g protein</span>}
                            {meal.carbs && <span>🌾 {meal.carbs}g carbs</span>}
                            {meal.fats && <span>🧈 {meal.fats}g fats</span>}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
