namespace GymSystem.API.DTOs;

public record TraineeProfileDto(
    int Id,
    int UserId,
    string FullName,
    string Email,
    string? Phone,
    string? ProfileImage,
    int? CoachId,
    string? CoachName,
    double? Height,
    double? Weight,
    int? Age,
    string? Gender,
    string? FitnessGoal,
    DateTime? TrainingStartDate,
    DateTime? TrainingEndDate,
    int? TrainingDurationMonths
);

public record UpdateTraineeProfileRequest(
    double? Height,
    double? Weight,
    int? Age,
    string? Gender,
    string? FitnessGoal,
    int? CoachId,
    int? TrainingDurationMonths
);

public record InBodyRecordDto(
    int Id,
    DateTime RecordDate,
    double Weight,
    double Height,
    double? BodyFatPercentage,
    double? MuscleMass,
    double? BMI,
    double? VisceralFat,
    double? WaterPercentage,
    double? BoneMass,
    string? Notes
);

public record CreateInBodyRequest(
    double Weight,
    double Height,
    double? BodyFatPercentage,
    double? MuscleMass,
    double? VisceralFat,
    double? WaterPercentage,
    double? BoneMass,
    string? Notes,
    string? AttachmentBase64,
    string? AttachmentType
);

public record NutritionPlanDto(
    int Id,
    string Title,
    string? Description,
    bool IsAutoGenerated,
    string? CoachName,
    DateTime CreatedAt,
    List<MealDto> Meals,
    string? AttachmentBase64,
    string? AttachmentType
);

public record MealDto(
    int Id,
    string MealName,
    string? Time,
    string? Foods,
    int? Calories,
    double? Protein,
    double? Carbs,
    double? Fats
);

public record CreateNutritionPlanRequest(
    int TraineeId,
    string Title,
    string? Description,
    string? AttachmentBase64,
    string? AttachmentType,
    List<CreateMealRequest> Meals
);

public record CreateMealRequest(
    string MealName,
    string? Time,
    string? Foods,
    int? Calories,
    double? Protein,
    double? Carbs,
    double? Fats
);

public record SubscribeRequest(int SubscriptionPlanId, int? CoachId = null);
public record ChangeCoachRequest(int? CoachId);

public record BodyStatsResult(
    double BMI,
    string BMICategory,
    double EstimatedBodyFat,
    string BodyFatCategory,
    double IdealWeight,
    int DailyCalories,
    int ProteinGrams,
    int CarbsGrams,
    int FatsGrams
);
