// <auto-generated />
using System;
using GymSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701234337_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymSystem.API.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("GymSystem.API.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPrivateTraineesPerMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("PrivateSessionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("GymSystem.API.Models.CoachingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MarkedByCoach")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CoachingSessions");
                });

            modelBuilder.Entity("GymSystem.API.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("GymSystem.API.Models.GymSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryImagesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMapsUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstaPay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VodafoneCash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GymSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "القاهرة، مصر",
                            Email = "",
                            GoogleMapsUrl = "",
                            GymName = "GymPro",
                            HeroSubtitle = "كل يوم خطوة نحو الأفضل",
                            HeroTitle = "مرحباً بك في جيمنا! 💪",
                            InstaPay = "01000000000",
                            Phone = "01000000000",
                            VodafoneCash = "01000000000",
                            WhatsApp = "201000000000",
                            WorkingHours = "6 صباحاً - 12 منتصف الليل",
                            YearsExperience = 0
                        });
                });

            modelBuilder.Entity("GymSystem.API.Models.InBodyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BMI")
                        .HasColumnType("float");

                    b.Property<double?>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("BoneMass")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("MuscleMass")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<double?>("VisceralFat")
                        .HasColumnType("float");

                    b.Property<double?>("WaterPercentage")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("InBodyRecords");
                });

            modelBuilder.Entity("GymSystem.API.Models.NutritionMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<double?>("Carbs")
                        .HasColumnType("float");

                    b.Property<double?>("Fats")
                        .HasColumnType("float");

                    b.Property<string>("Foods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NutritionPlanId")
                        .HasColumnType("int");

                    b.Property<double?>("Protein")
                        .HasColumnType("float");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NutritionPlanId");

                    b.ToTable("NutritionMeals");
                });

            modelBuilder.Entity("GymSystem.API.Models.NutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("TraineeId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("GymSystem.API.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InBodySessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<bool>("IncludesNutritionPlan")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesPrivateCoach")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMonths = 1,
                            Features = "دخول الجيم|12 سيشن في الشهر|InBody مرة واحدة",
                            InBodySessionsPerMonth = 1,
                            IncludesNutritionPlan = false,
                            IncludesPrivateCoach = false,
                            IsActive = true,
                            Name = "اشتراك عادي",
                            Price = 150m,
                            SessionsPerMonth = 12,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            DurationMonths = 1,
                            Features = "دخول الجيم|26 سيشن في الشهر|InBody مرتين|خطة غذائية",
                            InBodySessionsPerMonth = 2,
                            IncludesNutritionPlan = true,
                            IncludesPrivateCoach = false,
                            IsActive = true,
                            Name = "اشتراك بريميوم",
                            Price = 300m,
                            SessionsPerMonth = 26,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            DurationMonths = 1,
                            Features = "دخول الجيم|12 سيشن مع كوتش|InBody مرتين|خطة غذائية|تمارين خاصة",
                            InBodySessionsPerMonth = 2,
                            IncludesNutritionPlan = true,
                            IncludesPrivateCoach = true,
                            IsActive = true,
                            Name = "تدريب برايفت",
                            Price = 600m,
                            SessionsPerMonth = 12,
                            Type = 2
                        });
                });

            modelBuilder.Entity("GymSystem.API.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("FitnessGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<int?>("TrainingDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrainingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrainingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingStatus")
                        .HasColumnType("int");

                    b.Property<int>("TrialSessionsUsed")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("GymSystem.API.Models.TraineeExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("TraineeExercises");
                });

            modelBuilder.Entity("GymSystem.API.Models.TraineeSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfirmedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("RemainingInBodySessions")
                        .HasColumnType("int");

                    b.Property<int>("RemainingSessionsThisMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("TraineeId")
                        .IsUnique();

                    b.ToTable("TraineeSubscriptions");
                });

            modelBuilder.Entity("GymSystem.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 23, 43, 36, 988, DateTimeKind.Utc).AddTicks(9617),
                            Email = "admin@gym.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$6Uw7AQBs4mmYMAqOr7.8NuKwg/fJqtw939CRvQ64KgzjuB2fWS1ZW",
                            Role = 0
                        });
                });

            modelBuilder.Entity("GymSystem.API.Models.ChatMessage", b =>
                {
                    b.HasOne("GymSystem.API.Models.Trainee", "Trainee")
                        .WithMany("ChatMessages")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymSystem.API.Models.Coach", b =>
                {
                    b.HasOne("GymSystem.API.Models.User", "User")
                        .WithOne("CoachProfile")
                        .HasForeignKey("GymSystem.API.Models.Coach", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymSystem.API.Models.CoachingSession", b =>
                {
                    b.HasOne("GymSystem.API.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymSystem.API.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymSystem.API.Models.Exercise", b =>
                {
                    b.HasOne("GymSystem.API.Models.Coach", "Coach")
                        .WithMany("Exercises")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("GymSystem.API.Models.InBodyRecord", b =>
                {
                    b.HasOne("GymSystem.API.Models.Trainee", "Trainee")
                        .WithMany("InBodyRecords")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymSystem.API.Models.NutritionMeal", b =>
                {
                    b.HasOne("GymSystem.API.Models.NutritionPlan", "NutritionPlan")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("GymSystem.API.Models.NutritionPlan", b =>
                {
                    b.HasOne("GymSystem.API.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymSystem.API.Models.Trainee", "Trainee")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymSystem.API.Models.Trainee", b =>
                {
                    b.HasOne("GymSystem.API.Models.Coach", "Coach")
                        .WithMany("Trainees")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymSystem.API.Models.User", "User")
                        .WithOne("TraineeProfile")
                        .HasForeignKey("GymSystem.API.Models.Trainee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymSystem.API.Models.TraineeExercise", b =>
                {
                    b.HasOne("GymSystem.API.Models.Exercise", "Exercise")
                        .WithMany("TraineeExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymSystem.API.Models.Trainee", "Trainee")
                        .WithMany("TraineeExercises")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymSystem.API.Models.TraineeSubscription", b =>
                {
                    b.HasOne("GymSystem.API.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymSystem.API.Models.Trainee", "Trainee")
                        .WithOne("ActiveSubscription")
                        .HasForeignKey("GymSystem.API.Models.TraineeSubscription", "TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("GymSystem.API.Models.Coach", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("GymSystem.API.Models.Exercise", b =>
                {
                    b.Navigation("TraineeExercises");
                });

            modelBuilder.Entity("GymSystem.API.Models.NutritionPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("GymSystem.API.Models.Trainee", b =>
                {
                    b.Navigation("ActiveSubscription");

                    b.Navigation("ChatMessages");

                    b.Navigation("InBodyRecords");

                    b.Navigation("NutritionPlans");

                    b.Navigation("TraineeExercises");
                });

            modelBuilder.Entity("GymSystem.API.Models.User", b =>
                {
                    b.Navigation("CoachProfile");

                    b.Navigation("TraineeProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
