namespace GymSystem.API.Models;

public class NutritionPlan
{
    public int Id { get; set; }
    public int TraineeId { get; set; }
    public Trainee Trainee { get; set; } = null!;
    public int? CoachId { get; set; }
    public Coach? Coach { get; set; }
    public string Title { get; set; } = "";
    public string? Description { get; set; }
    public bool IsAutoGenerated { get; set; } = false;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public string? AttachmentBase64 { get; set; }
    public string? AttachmentType { get; set; } // "image", "pdf", "word"

    public ICollection<NutritionMeal> Meals { get; set; } = new List<NutritionMeal>();
}

public class NutritionMeal
{
    public int Id { get; set; }
    public int NutritionPlanId { get; set; }
    public NutritionPlan NutritionPlan { get; set; } = null!;
    public string MealName { get; set; } = "";
    public string? Time { get; set; }
    public string? Foods { get; set; }
    public int? Calories { get; set; }
    public double? Protein { get; set; }
    public double? Carbs { get; set; }
    public double? Fats { get; set; }
}
